- name: OS-specific tasks
  include_tasks: "{{ ansible_pkg_mgr|lower }}.yml"

- name: Generate certs
  command: "certbot certonly -n --agree-tos --standalone -d {{ ([item.cn] + item.domains) | join(',') }} -m {{ emails | join(',') }}"
  with_items: "{{ certs }}"

